<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <CopyLocalLockFileAssemblies>True</CopyLocalLockFileAssemblies>
    <EnforceExtendedAnalyzerRules>True</EnforceExtendedAnalyzerRules>
    <PackageScribanIncludeSource>true</PackageScribanIncludeSource>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" PrivateAssets="all" />
    <PackageReference Include="Scriban" Version="6.5.8" IncludeAssets="build" PrivateAssets="all">
      <NoWarn>NU1901;NU1902;NU1903;NU1904</NoWarn>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Templates\**" />
    <EmbeddedResource Include="Templates\**" />
  </ItemGroup>

</Project>
